vich_uploader:
    db_driver: orm

    mappings:
        bien-img:
           uri_prefix: /images/biens
           upload_destination: '%kernel.project_dir%/public/images/biens'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
